version: '3.8'

services:
  backend:
    image: andreybrumatti/stock-backend:3.0
    container_name: stock-backend
    ports:
      - "8082:8082"
    networks:
      - stock-network
    depends_on:
      - pgadmin
      - postgres

  postgres:
    image: bitnami/postgresql:latest
    container_name: inventory_control
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: stock_db
    ports:
      - "5432:5432"
    volumes:
      - stock_postgres_data:/var/lib/postgresql/data
    networks:
      - stock-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: stock_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@stock.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - stock-network

volumes:
  stock_postgres_data:

networks:
  stock-network:
    driver: bridge