version: '3.8'

services:



  postgres:
    image: bitnami/postgresql:latest

    container_name: inventory_control
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: stock_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - stock-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: stock_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@stock.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - stock-network

volumes:
  postgres_data:

networks:
  stock-network:
    driver: bridge